### ISSUE TITLE
Build fails with missing __apple_build_version__

### ISSUE THREAD

**Issue by jtippett** [Asmod4n/mruby-redis-ae#1]
The line here looks for `__apple_build_version__` for a version check: https://github.com/Asmod4n/mruby-redis-ae/blob/9256606beaff60168d1368771fda9101c5fcdd3c/src/atomicvar.h#L109

This fails on my machine (mac m2, OS 14.7, should be everything installed).

`mruby/build/repos/host/mruby-redis-ae/src/atomicvar.h:109:52: warning: '__apple_build_version__' is not defined, evaluates to 0 [-Wundef]`

This then leads to a cascade of other failures relating to atomic operations, the first of which is `mruby/build/repos/host/mruby-redis-ae/src/atomicvar.h:155:2: error: "Unable to determine atomic operations for your platform"`. The build fails.

 I suspect it may be because I am using clang installed from brew:
```
james@lagoon % clang -v
Homebrew clang version 16.0.5
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

Simply replacing the offending check with 1 "fixed" the issue but I presume this is not good enough. I tried to add another condition based on `__clang_version__` but that evaluates to a string (as seen above) and not sure what we're even checking here.

Since i'm pretty certain my build env is newer than the min version the code was checking for, simply skipping the check "works for me" but just FYI this is a thing.

**Comment by Asmod4n** [comment]
Try it with https://github.com/redis/redis/blob/unstable/src/atomicvar.h and see if it works.

**Comment by jtippett** [comment]
Tried with that and no it doesn't. Exactly the same issue. Shall I raise it over there?

**Comment by Asmod4n** [comment]
Yes, try and compile Redis beforehand though. There is a manual on how to do that there.

**Comment by jtippett** [comment]
Redis compiles fine - their build system is significantly different. It specifically detects for xcode here and calls it if present: https://github.com/redis/redis/blob/unstable/deps/jemalloc/build-aux/config.guess#L1367

Here's the first thing you see when you make:
```
james@black-lagoon redis % make
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make all
    CC Makefile.dep
```

The equivalent in mruby is here and will just return `clang` if it's a mac: https://github.com/mruby/mruby/blob/master/lib/mruby/build.rb#LL35C11-L35C71

When it does this, and the user also has clang installed elsewhere, the special apple constants aren't there and it fails.

Since this is apparently the first time this has ever happened, and it would be complex changing mruby's much simpler build system to support this edge case, I suppose it's not worth changing.
